//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatlabClient01 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="y", Namespace="http://schemas.datacontract.org/2004/07/MatlabSvc")]
    [System.SerializableAttribute()]
    public partial struct y : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CompletionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Completion {
            get {
                return this.CompletionField;
            }
            set {
                if ((this.CompletionField.Equals(value) != true)) {
                    this.CompletionField = value;
                    this.RaisePropertyChanged("Completion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatlabClient01.IMatlabInterface")]
    public interface IMatlabInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatlabInterface/callMATLABfunction_1", ReplyAction="http://tempuri.org/IMatlabInterface/callMATLABfunction_1Response")]
        MatlabClient01.y callMATLABfunction_1(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatlabInterface/callMATLABfunction_1", ReplyAction="http://tempuri.org/IMatlabInterface/callMATLABfunction_1Response")]
        System.Threading.Tasks.Task<MatlabClient01.y> callMATLABfunction_1Async(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatlabInterface/callMATLABfunction_2", ReplyAction="http://tempuri.org/IMatlabInterface/callMATLABfunction_2Response")]
        double[] callMATLABfunction_2(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatlabInterface/callMATLABfunction_2", ReplyAction="http://tempuri.org/IMatlabInterface/callMATLABfunction_2Response")]
        System.Threading.Tasks.Task<double[]> callMATLABfunction_2Async(double x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatlabInterfaceChannel : MatlabClient01.IMatlabInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatlabInterfaceClient : System.ServiceModel.ClientBase<MatlabClient01.IMatlabInterface>, MatlabClient01.IMatlabInterface {
        
        public MatlabInterfaceClient() {
        }
        
        public MatlabInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatlabInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatlabInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatlabInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MatlabClient01.y callMATLABfunction_1(double x) {
            return base.Channel.callMATLABfunction_1(x);
        }
        
        public System.Threading.Tasks.Task<MatlabClient01.y> callMATLABfunction_1Async(double x) {
            return base.Channel.callMATLABfunction_1Async(x);
        }
        
        public double[] callMATLABfunction_2(double x) {
            return base.Channel.callMATLABfunction_2(x);
        }
        
        public System.Threading.Tasks.Task<double[]> callMATLABfunction_2Async(double x) {
            return base.Channel.callMATLABfunction_2Async(x);
        }
    }
}
